baseURL = "https://shower-loop.github.io/"
languageCode = "en-us"
theme = "chocolate"
publishDir = "./"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
	weight = 1
	title = "Home"
  [[menu.main]]
    identifier = "how-it-works"
    name = "How It Works"
    url = "/how-it-works/"
	weight = 2
	title = "How It Works"
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
	weight = 3
	title = "Portfolio"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
	weight = 4
	title = "Posts"
  [[menu.main]]
    identifier = "contact"
    name = "Contact Us"
    url = "/contact-us/"
	weight = 5
	title = "Contact Us"
[params]
  facebookShareUrl = "https://www.facebook.com/sharer/sharer.php?u="
  twitterShareUrl = "http://twitter.com/share?url="
  redditShareUrl = "http://www.reddit.com/submit?url="
